### ISSUE TITLE
Setting sortable's moveType appears to have no effect

### ISSUE THREAD

**Issue by F21** [yui/yui3#1659]
I am trying to set a sortable's `moveType` to copy, however if I drag a node from the first list to the second list, a copy is not made.

http://jsfiddle.net/7Lbqg/

**Comment by wizhippo** [comment]
I have found the issue. `_onDropEnter` appends the node prior to `_onDragOver` firing. `_onDragOver`  tests if the node is already in the parentNode, and if it is does a swap instead of a copy.  This always results in a swap because as stated `_onDropEnter` alread appeded the node.
