### ISSUE TITLE
Website not working

### ISSUE THREAD

**Issue by sorcamarian** [yui/yui3#2020]
Hi,

Yesterday I tried to visit https://yuilibrary.com/ and it didn't work.
The error had something to do with the host Zeit Now, v1.

https://vercel.com/blog/zeit-is-now-vercel
![image](https://user-images.githubusercontent.com/12509753/90040521-b408b800-dcd0-11ea-82c9-1c5d5ee6a439.png)

**Comment by Remote-version-git** [comment]
I can't visit either.

**Comment by almaember1098** [comment]
I feel like this is final. The library has been abandoned back in 2014, I don't think it will get online again.

User the [internet archive](https://web.archive.org)

**Comment by erwanosouf** [comment]
Any ways to regenerate the full Web Site ?
API Docs can be regenerated using yuidoc but I can't find the User Guides / Examples

**Comment by almaember1098** [comment]
@erwanosouf you can try internet archive, maybe it's archived there

**Comment by almaember1098** [comment]
@erwanosouf here is a link: https://web.archive.org/web/20200704064537/https://yuilibrary.com/

**Comment by dragonDScript** [comment]
This project is no longer active, so you won't receive util answers anymore. Try another lib!

**Comment by almaember1098** [comment]
@dragonDScript certain people might have to deal with legacy projects etc. that still use yui

**Comment by dragonDScript** [comment]
🤔 So yui was popular some day?

**Comment by redonkulus** [comment]
Thanks for the interest and concern, we had previously had the old site on Vercel but when they deprecated their v1 platform we were left with a site that could no longer run. @clarle luckily refactored the old site to work on github pages. The yuilibrary.com domain will now redirect to his site. The ssl certs are still in progress but if you go to http://yuilibrary.com you should be redirect to the new location. Thanks!
