### ISSUE TITLE
Complete local build instructions

### ISSUE THREAD

**Issue by bf4** [yui/yui3#916]
I want to build all the modules locally so they're just [like what's on the CDN](http://yui.yahooapis.com/3.10.3/build/yui/yui.js) (so I can host them on my own server).  What steps are missing?

I followed the [instructions on the wiki](https://github.com/yui/yui3/wiki/Developer-Workflow#building-yui) and then some, but there's still some further processing the YUI team does before a release that I'm missing

```
git clone --depth=256 https://github.com/yui/yui3.git
cd yui3
git checkout v3.10.3
```

perhaps not necessary since I'm checking out a tags release, but

```
npm -g install shifter
npm -g install yogi
yogi build
cd build/
```

but then even if I try to add the version

```
find . -name '*.js' | xargs perl -pi -w -e 's/@VERSION@/3.10.3/g;'
```

I'm still missing things like the header in yui.js (not important, I suppose)

```
/*
YUI 3.10.3 (build 2fb5187)
Copyright 2013 Yahoo! Inc. All rights reserved.
Licensed under the BSD License.
http://yuilibrary.com/license/
*/
```
- in various places: `GALLERY_VERSION = 'gallery-2013.06.05-22-14',` vs. `'gallery-2013.06.20-02-07',`

and this makes me wonder how my tools might be different

```
-/* This file is auto-generated by (yogi.js loader --mix --yes) */
+/* This file is auto-generated by (yogi loader --yes --mix --start ../) */
```

**Comment by kostjerry** [comment]
Hi, @ezequiel!

1. I noticed that before `grunt release` you must also run 
```
npm i shifter
```

2. Is there any way to automatically (thru args) setup BASE url in the build?

3. I have run `grunt release` and got an error:
```
Running "npm-copy" task
Copying to build dir: /usr/local/www/static/vendor/yui3/build-npm
**Fatal error: Path must be a string. Received undefined**
```

Thanks!
